# Generated by Django 5.2.3 on 2025-06-12 10:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file_path', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomass.aoi')),
            ],
        ),
        migrations.CreateModel(
            name='BiomassRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('cog_url', models.TextField()),
                ('mean', models.FloatField()),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomass.aoi')),
            ],
        ),
        migrations.CreateModel(
            name='BiomassStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField()),
                ('total_mg', models.FloatField()),
                ('total_carbon', models.FloatField()),
                ('rmse_model', models.FloatField()),
                ('r2_model', models.FloatField()),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biomass.aoi')),
            ],
        ),
    ]
