# Generated by Django 5.2.3 on 2025-06-23 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomassstats',
            name='r2_model',
        ),
        migrations.RemoveField(
            model_name='biomassstats',
            name='rmse_model',
        ),
    ]
