# Generated by Django 5.2.3 on 2025-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomass', '0002_remove_biomassstats_r2_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomassstats',
            name='task_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
