# Generated by Django 5.2.3 on 2025-06-23 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biomass', '0003_biomassstats_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biomassstats',
            old_name='total_carbon',
            new_name='mean_carbon',
        ),
        migrations.RenameField(
            model_name='biomassstats',
            old_name='total_mg',
            new_name='mean_mg',
        ),
    ]
