# Generated by Django 5.2.3 on 2025-07-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomass', '0004_rename_total_carbon_biomassstats_mean_carbon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biomassstats',
            name='task_id',
        ),
        migrations.AddField(
            model_name='aoi',
            name='task_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
