# Generated by Django 5.2.3 on 2025-11-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomass', '0005_remove_biomassstats_task_id_aoi_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
