# Generated by Django 5.2.3 on 2025-11-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomass', '0006_aoi_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='share_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
