# Generated by Django 5.2.3 on 2025-11-12 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biomass', '0007_aoi_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoi',
            name='status',
            field=models.CharField(choices=[('analysing', 'Analysing'), ('completed', 'Completed'), ('error', 'Error')], default='analysing', max_length=20),
        ),
    ]
